### PR TITLE
National

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @layik just looking at this with @eugenividal, could be useful : )

**Comment by layik** [comment]
Accepted you mean? :)

**Comment by Robinlovelace** [comment]
No, it's not been released on CRAN yet. I added this new argument as it will be useful for Eugeni and, hopefully, others. I think it could be the basis of a function like `get_pct_national()`.

**Comment by layik** [comment]
Looks good to me, but will test after.

**Pull request merged**
